name: tiktok_ui
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.0
  chewie: ^1.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.3
  intl: ^0.17.0
  video_player: ^2.2.5


dependency_overrides:
  bloc: ^8.0.0-dev.2
  flutter_bloc: ^7.3.0
  provider: ^6.0.0


dev_dependencies:
  bloc_test: ^8.2.0
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: TikTokIcons
      fonts:
        - asset: assets/fonts/TikTokIcons.ttf
